server:
  port: 10009

spring:
  application:
    name: connect-provider
  main:
    allow-bean-definition-overriding: true  
  datasource:
    url: jdbc:mysql://localhost:3306/paintfriend?autoReconnect=true&characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    database: MYSQL
    show-sql: true              
    properties:
            hibernate:
                dialect : org.hibernate.dialect.MySQL5Dialect

#
dao:
  sql:
    dbType: MySQL
    template: freemarker
    path: classpath:config/sql/*.xml

application:
  uploadDir: upload2
  uploadRootDir: D:\\temp\\files_dir

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20000/eureka
  instance:
      hostname: connect-provider
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      preferIpAddress: true
    
    
    