spring:
  application:
    name: connect-server
  main:
    allow-bean-definition-overriding: true  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://129.204.161.205:20000/eureka
  instance:
      hostname: connect-server
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      preferIpAddress: true
    
    
mars:
  connect:
    port: 10013
    ip: 127.0.0.1
    fileServer: http://127.0.0.1/upload
  hazelcast:
    backup-count: 1
    time-to-live-seconds: 3600
